'use client';

import { useEffect } from 'react';

export default function PrivacyPage() {
  useEffect(() => {
    document.title = 'Privacy Policy - Notelert';
  }, []);

  return (
    <main className="legal-page">
      <div className="container">
        <div className="back-link">
          <a href="/">← Back to Home</a>
        </div>
        <article className="legal-content">
          <h1>Notelert Privacy Policy</h1>
          <p className="last-updated"><strong>Last Updated:</strong> December 2024</p>

          <section>
            <h2>1. Introduction</h2>
            <p>
              Notelert ("we", "our", "the application") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, share, and protect your personal information when you use our Notelert mobile application and related services.
            </p>
            <p>
              By using Notelert, you agree to the practices described in this policy. If you do not agree with this policy, please do not use our services.
            </p>
          </section>

          <section>
            <h2>2. Information We Collect</h2>
            
            <h3>2.1. Account Information</h3>
            <p>When you register and sign in to Notelert using Google Sign-In, we collect:</p>
            <ul>
              <li><strong>Email Address</strong>: Your email address associated with your Google account</li>
              <li><strong>Name</strong>: Your full name or display name from Google</li>
              <li><strong>User ID</strong>: A unique identifier generated by Google for your account</li>
              <li><strong>Profile Picture</strong>: If available in your Google account (optional)</li>
            </ul>

            <h3>2.2. Notification Information</h3>
            <p>To provide the reminder service, we collect and store:</p>
            <ul>
              <li><strong>Notification title and message</strong>: The content of your reminders</li>
              <li><strong>Scheduled date and time</strong>: When you want to receive notifications</li>
              <li><strong>Notification type</strong>: Whether it's a time-based or location-based notification</li>
              <li><strong>Notification status</strong>: Whether it has been read, completed, or canceled</li>
              <li><strong>Obsidian links</strong>: If the notification is linked to an Obsidian document</li>
            </ul>

            <h3>2.3. Location Information</h3>
            <p>For location-based notifications, we collect:</p>
            <ul>
              <li><strong>Saved locations</strong>: Addresses, place names, and geographic coordinates (latitude and longitude) that you manually save</li>
              <li><strong>Geofencing data</strong>: Information needed to trigger notifications when you enter or exit specific areas</li>
              <li><strong>Location permissions</strong>: We request access to your location in the foreground and background to provide location-based reminders</li>
            </ul>
            <p>
              <strong>Important Note</strong>: We do not continuously track your location in real-time. We only use location when:
            </p>
            <ul>
              <li>You create or edit a saved location</li>
              <li>The application needs to verify if you are inside or outside a specific geographic area to trigger a notification</li>
            </ul>

            <h3>2.4. Google Calendar Information (Optional)</h3>
            <p>If you connect your Google Calendar account, we collect:</p>
            <ul>
              <li><strong>OAuth access tokens</strong>: Access and refresh tokens to access your Google Calendar</li>
              <li><strong>Calendar events</strong>: Title, description, date and time of events created in your calendar</li>
              <li><strong>Event IDs</strong>: Identifiers of events created in Google Calendar linked to your notifications</li>
            </ul>
            <p>
              This information is used solely to synchronize your notifications with Google Calendar. You can disconnect Google Calendar at any time from the application settings.
            </p>

            <h3>2.5. Device Information</h3>
            <p>To provide push notifications and improve the service, we collect:</p>
            <ul>
              <li><strong>Device token</strong>: Unique identifier for sending push notifications to your device</li>
              <li><strong>Device type</strong>: Platform (iOS or Android) and device model</li>
              <li><strong>Operating system</strong>: Operating system version</li>
              <li><strong>Installation ID</strong>: Unique identifier of the application installation</li>
            </ul>

            <h3>2.6. Obsidian Plugin Information (Optional)</h3>
            <p>If you use the Obsidian plugin for Notelert:</p>
            <ul>
              <li><strong>Authentication token</strong>: A unique token generated to link your Notelert account with the Obsidian plugin</li>
              <li><strong>Token expiration date</strong>: When the authentication token expires</li>
              <li><strong>Token status</strong>: Whether the token is active or has been revoked</li>
            </ul>

            <h3>2.7. Premium Subscription Information</h3>
            <p>If you subscribe to Notelert Premium:</p>
            <ul>
              <li><strong>Subscription status</strong>: Whether you have an active subscription</li>
              <li><strong>Expiration date</strong>: When your subscription or trial period expires</li>
              <li><strong>Product ID</strong>: Identifier of the purchased subscription product</li>
              <li><strong>Payment information</strong>: Processed exclusively by Google Play Store or Apple App Store (we do not store credit card information)</li>
            </ul>

            <h3>2.8. Usage Information</h3>
            <p>We collect information about how you use the application:</p>
            <ul>
              <li><strong>Language preferences</strong>: Language selected in the application</li>
              <li><strong>Notification settings</strong>: Whether you have enabled push notifications, email notifications, etc.</li>
              <li><strong>Theme settings</strong>: Light/dark theme preference</li>
              <li><strong>Debug logs</strong>: Only if you enable debug mode (optional)</li>
            </ul>

            <h3>2.9. Technical Information</h3>
            <p>To diagnose issues and improve the service:</p>
            <ul>
              <li><strong>Error logs</strong>: Information about errors that occur in the application</li>
              <li><strong>Performance information</strong>: Application performance metrics (only in debug mode)</li>
            </ul>
          </section>

          <section>
            <h2>3. How We Use Your Information</h2>
            <p>We use the collected information to:</p>

            <h3>3.1. Provide the Service</h3>
            <ul>
              <li>Create, schedule, and send notifications according to your preferences</li>
              <li>Manage time-based and location-based reminders</li>
              <li>Synchronize notifications with Google Calendar (if enabled)</li>
              <li>Provide integration with the Obsidian plugin</li>
              <li>Manage your account and subscription</li>
            </ul>

            <h3>3.2. Improve the Service</h3>
            <ul>
              <li>Diagnose and resolve technical issues</li>
              <li>Analyze application usage to improve functionality</li>
              <li>Develop new features and capabilities</li>
            </ul>

            <h3>3.3. Communication</h3>
            <ul>
              <li>Send push notifications about your reminders</li>
              <li>Send email notifications (only if enabled and you have a Premium subscription)</li>
              <li>Respond to your inquiries and support requests</li>
            </ul>

            <h3>3.4. Legal Compliance</h3>
            <ul>
              <li>Comply with legal obligations</li>
              <li>Protect our rights and prevent fraud</li>
              <li>Respond to valid legal requests</li>
            </ul>
          </section>

          <section>
            <h2>4. Third-Party Services</h2>
            <p>Notelert uses the following third-party services that may collect information:</p>

            <h3>4.1. Google Services</h3>
            <ul>
              <li><strong>Google Sign-In</strong>: For authentication and account creation
                <br/>Privacy Policy: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>
              </li>
              <li><strong>Google Calendar API</strong>: To synchronize events with your calendar (optional)
                <br/>Privacy Policy: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>
              </li>
              <li><strong>Google Maps API</strong>: For address search and geocoding
                <br/>Privacy Policy: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>
              </li>
            </ul>

            <h3>4.2. Firebase (Google Cloud Platform)</h3>
            <p>We use Firebase for:</p>
            <ul>
              <li><strong>Firebase Authentication</strong>: User authentication</li>
              <li><strong>Cloud Firestore</strong>: Storage of user data, notifications, locations, and tokens</li>
              <li><strong>Cloud Functions</strong>: Server-side processing and business logic</li>
              <li><strong>Firebase Cloud Messaging (FCM)</strong>: Push notification delivery</li>
            </ul>
            <p>Firebase Privacy Policy: <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer">https://firebase.google.com/support/privacy</a></p>

            <h3>4.3. Expo</h3>
            <p>We use Expo for application development and distribution:</p>
            <ul>
              <li><strong>Expo Updates</strong>: Application updates</li>
              <li><strong>Expo Notifications</strong>: Local notification management</li>
              <li><strong>Expo Location</strong>: Location services</li>
            </ul>
            <p>Expo Privacy Policy: <a href="https://expo.dev/privacy" target="_blank" rel="noopener noreferrer">https://expo.dev/privacy</a></p>

            <h3>4.4. Google Play Store / Apple App Store</h3>
            <p>For Premium subscriptions, payment processing is handled through:</p>
            <ul>
              <li><strong>Google Play Billing</strong>: For Android devices</li>
              <li><strong>Apple App Store In-App Purchases</strong>: For iOS devices</li>
            </ul>
            <p>These services process your payment information. We do not store or have access to credit card information.</p>
          </section>

          <section>
            <h2>5. Information Sharing</h2>
            <p>We do not sell, rent, or share your personal information with third parties for their own marketing purposes.</p>
            <p>We share information only in the following circumstances:</p>

            <h3>5.1. Service Providers</h3>
            <p>We share information with service providers who help us operate the application, such as:</p>
            <ul>
              <li>Google (Firebase, Google Sign-In, Google Calendar, Google Maps)</li>
              <li>Expo (development platform)</li>
              <li>Hosting and cloud service providers</li>
            </ul>
            <p>These providers are contractually obligated to protect your information and may only use it for specified purposes.</p>

            <h3>5.2. Legal Compliance</h3>
            <p>We may disclose information if necessary to:</p>
            <ul>
              <li>Comply with a court order, subpoena, or legal process</li>
              <li>Respond to government requests</li>
              <li>Protect our rights, privacy, security, or property</li>
              <li>Prevent fraud or illegal activity</li>
            </ul>

            <h3>5.3. Business Transfers</h3>
            <p>In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction.</p>
          </section>

          <section>
            <h2>6. Data Security</h2>
            <p>We implement technical and organizational security measures to protect your information:</p>

            <h3>6.1. Technical Measures</h3>
            <ul>
              <li><strong>Encryption in transit</strong>: All communications use HTTPS/TLS</li>
              <li><strong>Encryption at rest</strong>: Sensitive data is stored encrypted in Firebase</li>
              <li><strong>Authentication</strong>: Data access protected by user authentication</li>
              <li><strong>Security rules</strong>: Firestore Security Rules ensure only you can access your data</li>
              <li><strong>Secure tokens</strong>: Authentication tokens are stored securely</li>
            </ul>

            <h3>6.2. Organizational Measures</h3>
            <ul>
              <li><strong>Limited access</strong>: Only authorized personnel have access to data</li>
              <li><strong>Regular audits</strong>: We regularly review and update our security practices</li>
              <li><strong>Monitoring</strong>: We monitor data access to detect suspicious activity</li>
            </ul>

            <h3>6.3. Limitations</h3>
            <p>Although we implement robust security measures, no method of transmission or storage is 100% secure. We cannot guarantee absolute security of your information.</p>
          </section>

          <section>
            <h2>7. Data Retention</h2>

            <h3>7.1. Active Data</h3>
            <p>We retain your information while:</p>
            <ul>
              <li>Your account is active</li>
              <li>We need to provide the service</li>
              <li>It is necessary to comply with legal obligations</li>
            </ul>

            <h3>7.2. Account Deletion</h3>
            <p>When you delete your account:</p>
            <ul>
              <li>We permanently delete all your personal data from our servers</li>
              <li>We delete all notifications, locations, and associated tokens</li>
              <li>We delete Google Calendar events created by Notelert (if connected)</li>
              <li>We delete device information</li>
            </ul>
            <p><strong>Note</strong>: Some data may remain in backups for a limited period before being permanently deleted.</p>

            <h3>7.3. Anonymous Data</h3>
            <p>We may retain anonymized and aggregated data that does not personally identify any user for analytical and service improvement purposes.</p>
          </section>

          <section>
            <h2>8. Your Rights (GDPR and CCPA)</h2>
            <p>If you reside in the European Union, California, or other jurisdictions with data protection laws, you have the following rights:</p>

            <h3>8.1. Right of Access</h3>
            <p>You can request a copy of all personal data we have about you. You can export your data directly from the application in Settings &gt; Export Data.</p>

            <h3>8.2. Right of Rectification</h3>
            <p>You can correct or update your information at any time through the application or by contacting us.</p>

            <h3>8.3. Right to Deletion ("Right to be Forgotten")</h3>
            <p>You can request deletion of your account and all your personal data. You can do this from the application in Settings &gt; Delete Account.</p>

            <h3>8.4. Right to Object</h3>
            <p>You can object to the processing of your personal data for certain purposes. You can disable specific features in the application settings.</p>

            <h3>8.5. Right to Data Portability</h3>
            <p>You can request that your data be transferred to another service provider. You can export your data from the application.</p>

            <h3>8.6. Right to Restriction</h3>
            <p>You can request that we limit the processing of your personal data in certain circumstances.</p>

            <h3>8.7. Withdraw Consent</h3>
            <p>You can withdraw your consent for data processing at any time by disabling specific features or deleting your account.</p>

            <p>To exercise these rights, you can:</p>
            <ol>
              <li>Use the built-in features in the application</li>
              <li>Contact us at: <a href="mailto:joaquim.frances@protonmail.com">joaquim.frances@protonmail.com</a></li>
            </ol>
            <p>We will respond to your request within 30 days.</p>
          </section>

          <section>
            <h2>9. Application Permissions</h2>
            <p>Notelert requests the following permissions:</p>

            <h3>9.1. Location</h3>
            <ul>
              <li><strong>Foreground location</strong>: To create and manage saved locations</li>
              <li><strong>Background location</strong>: To trigger notifications when you enter or exit specific geographic areas</li>
            </ul>
            <p><strong>Usage</strong>: These permissions are essential for location-based notifications. You can disable location access in your device settings, but this will limit the functionality of location-based notifications.</p>

            <h3>9.2. Notifications</h3>
            <ul>
              <li><strong>Push notifications</strong>: To send reminders and alerts</li>
              <li><strong>Local notifications</strong>: To schedule notifications on the device</li>
            </ul>
            <p><strong>Usage</strong>: Essential for the main functionality of the application.</p>

            <h3>9.3. Internet and Network</h3>
            <ul>
              <li><strong>Internet access</strong>: To synchronize data with our servers</li>
              <li><strong>Network status</strong>: To verify connectivity</li>
            </ul>
            <p><strong>Usage</strong>: Necessary to synchronize notifications, locations, and account data.</p>

            <h3>9.4. Local Storage</h3>
            <ul>
              <li><strong>Device storage</strong>: To save preferences and cache data locally</li>
            </ul>
            <p><strong>Usage</strong>: Improves performance and allows partial offline functionality.</p>
          </section>

          <section>
            <h2>10. Cookies and Similar Technologies</h2>
            <p>Notelert is a mobile application and does not use traditional cookies. However, we use similar technologies:</p>
            <ul>
              <li><strong>Authentication tokens</strong>: To keep you signed in</li>
              <li><strong>Local storage</strong>: To save preferences and cache data</li>
              <li><strong>Device identifiers</strong>: To send push notifications</li>
            </ul>
            <p>These technologies are essential for the application to function.</p>
          </section>

          <section>
            <h2>11. Children's Privacy</h2>
            <p>
              Notelert is not directed to children under 13 years of age (or the minimum age required in your jurisdiction). We do not knowingly collect personal information from children. If we discover that we have collected information from a child, we will delete it immediately.
            </p>
            <p>
              If you are a parent or guardian and believe your child has provided us with personal information, please contact us immediately.
            </p>
          </section>

          <section>
            <h2>12. International Data Transfers</h2>
            <p>Your data may be processed and stored on servers located outside your country of residence, including:</p>
            <ul>
              <li>United States (Firebase/Google Cloud)</li>
              <li>Other countries where our service providers operate</li>
            </ul>
            <p>By using Notelert, you consent to the transfer of your data to these countries. We implement appropriate safeguards to protect your information in accordance with this policy.</p>
          </section>

          <section>
            <h2>13. Changes to this Privacy Policy</h2>
            <p>We may update this Privacy Policy from time to time. We will notify you of significant changes by:</p>
            <ul>
              <li>Posting the new policy in the application</li>
              <li>Sending a push notification (if enabled)</li>
              <li>Updating the "Last Updated" date at the top</li>
            </ul>
            <p>We encourage you to review this policy periodically. Continued use of Notelert after changes constitutes your acceptance of the revised policy.</p>
          </section>

          <section>
            <h2>14. Contact</h2>
            <p>If you have questions, concerns, or requests related to this Privacy Policy or the processing of your personal data, you can contact us:</p>
            <p>
              <strong>Email</strong>: <a href="mailto:joaquim.frances@protonmail.com">joaquim.frances@protonmail.com</a>
            </p>
            <p>We will respond to your inquiry as soon as possible, generally within 30 days.</p>
          </section>

          <section>
            <h2>15. Legal Basis for Processing (GDPR)</h2>
            <p>For users in the European Union, we process your personal data based on:</p>
            <ul>
              <li><strong>Consent</strong>: When you accept this policy and use optional features (such as Google Calendar)</li>
              <li><strong>Contract performance</strong>: To provide the service you have requested</li>
              <li><strong>Legitimate interest</strong>: To improve the service, prevent fraud, and ensure security</li>
              <li><strong>Legal obligation</strong>: To comply with legal requirements</li>
            </ul>
          </section>

          <section>
            <h2>16. Additional Information</h2>

            <h3>16.1. Data Not Collected</h3>
            <p>We do not collect:</p>
            <ul>
              <li>Contact information from your address book</li>
              <li>Content of your messages or emails (except those you send through Notelert)</li>
              <li>Information from other applications installed on your device</li>
              <li>Biometric information</li>
            </ul>

            <h3>16.2. Data Shared with Obsidian Plugin</h3>
            <p>If you use the Obsidian plugin for Notelert:</p>
            <ul>
              <li>The plugin can access your notifications through a secure authentication token</li>
              <li>The plugin does not have access to your complete account information</li>
              <li>You can revoke the plugin's access at any time from the application</li>
            </ul>

            <h3>16.3. Email Notifications</h3>
            <p>Email notifications (Premium feature) are sent through our servers. Your email address is used solely for this purpose and is not shared with third parties for marketing.</p>
          </section>
        </article>
      </div>
      <style jsx>{`
        .legal-page {
          padding: 8rem 2rem 4rem;
          min-height: 100vh;
          background: var(--bg-primary);
        }

        .container {
          max-width: 900px;
          margin: 0 auto;
        }

        .legal-content {
          background: var(--bg-secondary);
          border-radius: 16px;
          padding: 3rem;
          border: 1px solid var(--border-subtle);
        }

        h1 {
          font-size: 2.5rem;
          margin-bottom: 1rem;
          color: var(--text-normal);
          background: linear-gradient(to right, var(--primary-color), var(--accent-color));
          background-clip: text;
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .last-updated {
          color: var(--text-muted);
          margin-bottom: 3rem;
          font-size: 0.95rem;
        }

        section {
          margin-bottom: 3rem;
        }

        h2 {
          font-size: 1.8rem;
          margin-bottom: 1rem;
          margin-top: 2rem;
          color: var(--text-normal);
        }

        h3 {
          font-size: 1.3rem;
          margin-bottom: 0.75rem;
          margin-top: 1.5rem;
          color: var(--text-normal);
        }

        p {
          color: var(--text-muted);
          line-height: 1.8;
          margin-bottom: 1rem;
        }

        ul, ol {
          color: var(--text-muted);
          line-height: 1.8;
          margin-bottom: 1rem;
          padding-left: 2rem;
        }

        li {
          margin-bottom: 0.5rem;
        }

        a {
          color: var(--primary-color);
          text-decoration: none;
          transition: color 0.2s;
        }

        a:hover {
          color: var(--accent-color);
          text-decoration: underline;
        }

        strong {
          color: var(--text-normal);
        }

        .back-link {
          margin-bottom: 2rem;
        }

        .back-link a {
          color: var(--text-accent);
          text-decoration: none;
          font-weight: 500;
          transition: color 0.2s;
        }

        .back-link a:hover {
          color: var(--primary-color);
        }

        @media (max-width: 768px) {
          .legal-page {
            padding: 6rem 1rem 2rem;
          }

          .legal-content {
            padding: 2rem 1.5rem;
          }

          h1 {
            font-size: 2rem;
          }

          h2 {
            font-size: 1.5rem;
          }

          h3 {
            font-size: 1.2rem;
          }
        }
      `}</style>
    </main>
  );
}
