'use client';

import { useEffect } from 'react';

export default function PrivacyPage() {
  useEffect(() => {
    document.title = 'Privacy Policy - Notelert';
  }, []);

  return (
    <main className="legal-page">
      <div className="container">
        <div className="back-link">
          <a href="/">← Back to Home</a>
        </div>
        <article className="legal-content">
          <h1>Notelert Privacy Policy</h1>
          <p className="last-updated"><strong>Last updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

          <section>
            <h2>1. Introduction</h2>
            <p>
              Notelert ("we", "our", or "the application") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you use our Notelert mobile application and Obsidian plugin.
            </p>
            <p>
              By using Notelert, you agree to the practices described in this policy. If you do not agree with this policy, please do not use our application.
            </p>
          </section>

          <section>
            <h2>2. Data Controller</h2>
            <p>
              <strong>Controller:</strong> Joaquim Frances<br/>
              <strong>Contact Email:</strong> <a href="mailto:contact@notelert.com">contact@notelert.com</a><br/>
              <strong>Application:</strong> Notelert (com.quim79.notelert)
            </p>
          </section>

          <section>
            <h2>3. Information We Collect</h2>
            
            <h3>3.1. Authentication Information</h3>
            <p>When you register using Google Sign-In, we collect:</p>
            <ul>
              <li><strong>Google User ID</strong> (unique identifier)</li>
              <li><strong>Email address</strong></li>
              <li><strong>Name</strong> (if available in your Google account)</li>
              <li><strong>Profile picture</strong> (if available in your Google account)</li>
            </ul>

            <h3>3.2. Notification Content</h3>
            <p>When you create reminders, we store:</p>
            <ul>
              <li><strong>Notification title</strong> (may contain personal information you enter)</li>
              <li><strong>Notification message</strong> (may contain personal information you enter)</li>
              <li><strong>Scheduled date and time</strong></li>
              <li><strong>Unique notification identifier</strong></li>
            </ul>

            <h3>3.3. Location Data</h3>
            <p>For location-based notifications (geofencing), we collect:</p>
            <ul>
              <li><strong>Latitude and longitude coordinates</strong> of locations you select</li>
              <li><strong>Approximate address</strong> of the location</li>
              <li><strong>Activation type</strong> (on arrival or departure)</li>
            </ul>
            <p>
              <strong>Important:</strong> We do not continuously track your location in real-time. We only use location when you create a location-based notification and when the system detects that you have entered or left a specific zone you have defined.
            </p>

            <h3>3.4. In-App Purchase Data</h3>
            <p>If you purchase a Premium subscription, we store:</p>
            <ul>
              <li><strong>Subscription status</strong> (Premium/Free)</li>
              <li><strong>Subscription expiration date</strong></li>
              <li><strong>Product ID purchased</strong></li>
              <li><strong>Google Play purchase token</strong> (for verification)</li>
              <li><strong>Transaction ID</strong></li>
              <li><strong>Activation date</strong></li>
            </ul>

            <h3>3.5. Obsidian Plugin Data</h3>
            <p>When you use the Obsidian plugin, we process:</p>
            <ul>
              <li><strong>Plugin authentication token</strong> (generated by you from the mobile application)</li>
              <li><strong>Content of specific lines</strong> that you explicitly select to create reminders</li>
              <li><strong>We do not scan or access your complete vault</strong> - we only process the information you explicitly select</li>
            </ul>

            <h3>3.6. Technical Data</h3>
            <p>We automatically collect:</p>
            <ul>
              <li><strong>Unique device identifier</strong> (for push notifications)</li>
              <li><strong>Application information</strong> (version, operating system)</li>
              <li><strong>Error logs</strong> (to improve the application)</li>
            </ul>
          </section>

          <section>
            <h2>4. How We Use Your Information</h2>
            <p>We use your personal information to:</p>
            <ol>
              <li><strong>Provide the service:</strong>
                <ul>
                  <li>Authentication and account management</li>
                  <li>Create and manage your reminders</li>
                  <li>Send push notifications and emails according to your preferences</li>
                  <li>Process and verify in-app purchases</li>
                  <li>Integration with Obsidian through the plugin</li>
                </ul>
              </li>
              <li><strong>Improve the service:</strong>
                <ul>
                  <li>Analyze errors and technical issues</li>
                  <li>Develop new features</li>
                </ul>
              </li>
              <li><strong>Communication:</strong>
                <ul>
                  <li>Send scheduled reminder emails</li>
                  <li>Notifications about your account status</li>
                </ul>
              </li>
              <li><strong>Legal compliance:</strong>
                <ul>
                  <li>Comply with legal obligations</li>
                  <li>Respond to legal requests</li>
                </ul>
              </li>
            </ol>
          </section>

          <section>
            <h2>5. Legal Basis for Processing (GDPR)</h2>
            <p>For users in the European Union, we process your personal data based on:</p>
            <ul>
              <li><strong>Consent:</strong> By registering and using the application, you consent to the processing of your personal data.</li>
              <li><strong>Contract performance:</strong> Processing is necessary to provide the service you have requested (creating and sending reminders).</li>
              <li><strong>Legitimate interest:</strong> Service improvement and fraud prevention.</li>
            </ul>
          </section>

          <section>
            <h2>6. Sharing Information with Third Parties</h2>
            <p>We share your information with the following service providers:</p>

            <h3>6.1. Google (Authentication)</h3>
            <ul>
              <li><strong>Service:</strong> Google Sign-In</li>
              <li><strong>Data shared:</strong> User ID, email, name, photo</li>
              <li><strong>Purpose:</strong> User authentication</li>
              <li><strong>Privacy policy:</strong> <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a></li>
            </ul>

            <h3>6.2. Google Firebase</h3>
            <ul>
              <li><strong>Service:</strong> Firebase (Firestore, Cloud Functions)</li>
              <li><strong>Data shared:</strong> All data mentioned in section 3</li>
              <li><strong>Purpose:</strong> Data storage and processing</li>
              <li><strong>Privacy policy:</strong> <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer">https://firebase.google.com/support/privacy</a></li>
            </ul>

            <h3>6.3. Resend</h3>
            <ul>
              <li><strong>Service:</strong> Email delivery</li>
              <li><strong>Data shared:</strong> Email address, notification title and message</li>
              <li><strong>Purpose:</strong> Sending reminder emails</li>
              <li><strong>Privacy policy:</strong> <a href="https://resend.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">https://resend.com/legal/privacy-policy</a></li>
            </ul>

            <h3>6.4. Google Play</h3>
            <ul>
              <li><strong>Service:</strong> In-app purchase verification</li>
              <li><strong>Data shared:</strong> Purchase token, product ID</li>
              <li><strong>Purpose:</strong> Verify the validity of Premium purchases</li>
              <li><strong>Privacy policy:</strong> <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a></li>
            </ul>

            <p><strong>We do not sell or rent your personal information to third parties for commercial purposes.</strong></p>
          </section>

          <section>
            <h2>7. Data Security</h2>
            <p>We implement technical and organizational security measures to protect your data:</p>
            <ul>
              <li><strong>Encryption:</strong> Data is transmitted over encrypted connections (HTTPS)</li>
              <li><strong>Authentication:</strong> Restricted access through Firebase authentication</li>
              <li><strong>Security rules:</strong> Firestore configured with rules that limit access to your own data</li>
              <li><strong>Secure storage:</strong> Data stored on secure Google Cloud servers</li>
              <li><strong>Plugin tokens:</strong> 64-character tokens generated securely, with automatic expiration</li>
            </ul>
            <p>
              However, no method of transmission over the Internet or electronic storage is 100% secure. We cannot guarantee absolute security of your data.
            </p>
          </section>

          <section>
            <h2>8. Data Retention</h2>
            <ul>
              <li><strong>Account data:</strong> Retained while your account is active. You can delete your account at any time from the application.</li>
              <li><strong>Notifications:</strong> Automatically deleted after being sent or when you manually delete them.</li>
              <li><strong>Scheduled emails:</strong> Deleted after being sent or when cancelled.</li>
              <li><strong>Purchase data:</strong> Retained as required by law (generally 7 years for tax purposes).</li>
              <li><strong>Plugin tokens:</strong> Automatically deleted after 90 days or when the Premium subscription expires.</li>
            </ul>
          </section>

          <section>
            <h2>9. Your Rights (GDPR)</h2>
            <p>If you reside in the European Union, you have the following rights:</p>
            <ol>
              <li><strong>Right of access:</strong> You can request a copy of your personal data.</li>
              <li><strong>Right to rectification:</strong> You can correct inaccurate data.</li>
              <li><strong>Right to erasure:</strong> You can request deletion of your data.</li>
              <li><strong>Right to data portability:</strong> You can request a copy of your data in a structured format.</li>
              <li><strong>Right to object:</strong> You can object to the processing of your data.</li>
              <li><strong>Right to restrict processing:</strong> You can request that we limit the use of your data.</li>
              <li><strong>Right to withdraw consent:</strong> You can withdraw your consent at any time.</li>
            </ol>
            <p>To exercise these rights, contact us at: <a href="mailto:contact@notelert.com">contact@notelert.com</a></p>
          </section>

          <section>
            <h2>10. Minors</h2>
            <p>
              Notelert is not directed to minors under 16 years of age. We do not knowingly collect personal information from minors under 16. If we discover that we have collected information from a minor without parental consent, we will take steps to delete that information.
            </p>
          </section>

          <section>
            <h2>11. International Transfers</h2>
            <p>
              Your data may be transferred and stored on servers located outside your country of residence, including the United States. These countries may have different data protection laws. By using Notelert, you consent to these transfers.
            </p>
          </section>

          <section>
            <h2>12. Changes to this Policy</h2>
            <p>
              We may update this Privacy Policy occasionally. We will notify you of any changes by posting the new policy on this page and updating the "Last updated" date. We recommend that you review this policy periodically.
            </p>
          </section>

          <section>
            <h2>13. Contact</h2>
            <p>If you have questions about this Privacy Policy or how we handle your data, you can contact us at:</p>
            <p>
              <strong>Email:</strong> <a href="mailto:contact@notelert.com">contact@notelert.com</a><br/>
              <strong>Subject:</strong> Privacy Inquiry
            </p>
          </section>
        </article>
      </div>
      <style jsx>{`
        .legal-page {
          padding: 8rem 2rem 4rem;
          min-height: 100vh;
          background: var(--bg-primary);
        }

        .container {
          max-width: 900px;
          margin: 0 auto;
        }

        .legal-content {
          background: var(--bg-secondary);
          border-radius: 16px;
          padding: 3rem;
          border: 1px solid var(--border-subtle);
        }

        h1 {
          font-size: 2.5rem;
          margin-bottom: 1rem;
          color: var(--text-normal);
          background: linear-gradient(to right, var(--primary-color), var(--accent-color));
          background-clip: text;
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .last-updated {
          color: var(--text-muted);
          margin-bottom: 3rem;
          font-size: 0.95rem;
        }

        section {
          margin-bottom: 3rem;
        }

        h2 {
          font-size: 1.8rem;
          margin-bottom: 1rem;
          margin-top: 2rem;
          color: var(--text-normal);
        }

        h3 {
          font-size: 1.3rem;
          margin-bottom: 0.75rem;
          margin-top: 1.5rem;
          color: var(--text-normal);
        }

        p {
          color: var(--text-muted);
          line-height: 1.8;
          margin-bottom: 1rem;
        }

        ul, ol {
          color: var(--text-muted);
          line-height: 1.8;
          margin-bottom: 1rem;
          padding-left: 2rem;
        }

        li {
          margin-bottom: 0.5rem;
        }

        a {
          color: var(--primary-color);
          text-decoration: none;
          transition: color 0.2s;
        }

        a:hover {
          color: var(--accent-color);
          text-decoration: underline;
        }

        strong {
          color: var(--text-normal);
        }

        .back-link {
          margin-bottom: 2rem;
        }

        .back-link a {
          color: var(--text-accent);
          text-decoration: none;
          font-weight: 500;
          transition: color 0.2s;
        }

        .back-link a:hover {
          color: var(--primary-color);
        }

        @media (max-width: 768px) {
          .legal-page {
            padding: 6rem 1rem 2rem;
          }

          .legal-content {
            padding: 2rem 1.5rem;
          }

          h1 {
            font-size: 2rem;
          }

          h2 {
            font-size: 1.5rem;
          }

          h3 {
            font-size: 1.2rem;
          }
        }
      `}</style>
    </main>
  );
}
